[package]
name = "cantdrown"
version = "0.1.0"
authors = ["charlie <charlieschuy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
http = "0.2"
rand = "0.8"
regex = "1"
serenity = { version = "0.10", features = ["voice"] }
songbird = { version = "0.1", features = ["builtin-queue"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "signal"] }
zip = "0.5"
