[package]
name = "cantdrown"
version = "0.1.0"
authors = ["charlie <charlieschuy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
rand = "0.8"
serenity = { version = "0.10", features = ["voice"] }
songbird = "0.1"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "signal"] }